### ISSUE TITLE
Por que un sigleton?

### ISSUE THREAD

**Issue by mnavarrocarter** [fenriz07/Golang-Transbank-WebPay-Rest#6]
Estaba revisando esta librería porque necesito una para Go, pero no me convence mucho.

No me gusta tanto el estado global y el singleton que tienes para el ambiente y el cliente.

Por qué la diseñaste así? Has pensado en un struct `Client` que tenga una instancia de `http.Client` dentro, con el api key y el commerce code, y distintos factories de acuerdo al ambiente?

Lo otro es que tienes demasiados paquetes y archivos para una implementación que no debería ser tan grande.

Sorry, no intento ser pesado. Solo quiero saber si has pensando en un diseño alternativo o si la hiciste así a propósito, y por qué.

Saludos!

**Comment by fenriz07** [comment]
Hello Matias

Thanks for your comment. if you have a good idea. You can fork this repository and send your PR. 

Regards
